from . import diagnosis_department
from . import diagonosis
from . import brokers_info
from . import doctors_profile
from . import diagnosis_group
from . import patient_info
from . import leih_admission
from . import leih_admission_line
from . import bill_register_admission_line
from . import admission_payment_line
from . import patient_guarantor
from . import admission_payment
from . import admission_payment_configuration
from . import admission_payment_configuration_line
from . import admission_release
from . import advance_cash
from . import ambulance_registration
from . import ambulance_booking
from . import ambulance_expense
from . import appointment_booking
from . import appointment_paid
from . import appointment_payment
from . import appointment_payment_line
from . import add_bill
from . import bill_register
from . import bill_journal_relation
from . import investigation_payment
from . import investigation_payment_line
from . import bill_register_payment
from . import blood_donar
from . import blood_receiver
from . import cash_collection
from . import cash_collection_line
from . import custom_report_wiz
from . import hospital_dashboard
from . import diagnosis_room
from . import corporate_discount
from . import discount
from . import discount_line
from . import discount_category
from . import discount_configuration
from . import discount_configuration_line
from . import tube_color
from . import lab_method
from . import lab_instrument
from . import lab_antibiotic
from . import lab_specimen
from . import lab_report_block
from . import examination_report_template
from . import examination_possible_value
from . import examination_entry
from . import examination_entry_line
from . import examination_support_item
from . import examination_result
from . import examination_result_line
from . import examination_result_antibiogram_line
from . import lab_print_confirm
from . import examination_merge_line
from . import sample_type
from . import leih_expense
from . import admission_charge_item
from . import hospital_admission
from . import hospital_admission_line
from . import bill_register_general_admission_line
from . import general_admission_payment_line
from . import hospital_bed_line
from . import doctor_profile_admission_line
from . import hospital_medicine_line
from . import hospital_bill_line
from . import hospital_bed
from . import hospital_patient_guarantor
from . import hospital_medicine
from . import hospital_admission_payment
from . import general_admission_release
from . import inventory_product_entry
from . import inventory_product_entry_line
from . import inventory_requisition
from . import inventory_requisition_line
from . import laundry_clean
from . import laundry_clean_line
from . import laundry_receive
from . import laundry_laundry
from . import laundry_product
from . import leih_money_receipt
from . import opd_ticket
from . import opd_ticket_line
from . import opd_ticket_entry
from . import optics_sale
from . import optics_lens_sale_line
from . import optics_sale_payment_line
from . import product_lens
from . import optics_sale_payment
from . import examine_package
from . import examine_package_line
from . import payment_type
from . import diagnosis_sticker
from . import diagnosis_sticker_line
from . import ward_managment
from . import cc_collection
from . import detail_component
from . import optics_daily_collection
from . import leih_collection_report
from . import res_company
