from odoo import models, fields

class LeihAdmission(models.Model):
    _name = 'leih.admission'
    _description = 'LeihAdmission'

    name = fields.Char('Name')
    mobile = fields.Char(string='Mobile', store=False)
    patient_id = fields.Char(related='patient_name.patient_id', string='Patient Id')
    patient_name = fields.Many2one('patient.info', string='Patient Name')
    address = fields.Char('Address', store=False)
    age = fields.Char('Age', store=False)
    sex = fields.Char('Sex', store=False)
    ref_doctors = fields.Many2one('doctors.profile', string='Reffered by')
    operation_date = fields.Date('Operation Date')
    release_note = fields.Text('Release Note')
    package_name = fields.Many2one('examine.package', string='Package')
    leih_admission_line_id = fields.One2many('leih.admission.line', 'leih_admission_id')
    guarantor_line_id = fields.One2many('patient.guarantor', 'admission_id')
    bill_register_admission_line_id = fields.One2many('bill.register.admission.line', 'admission_line_id')
    admission_payment_line_id = fields.One2many('admission.payment.line', 'admission_payment_line_id')
    admission_journal_relation_id = fields.One2many('bill.journal.relation', 'admission_journal_relation_id')
    emergency = fields.Boolean('Emergency Department')
    total_without_discount = fields.Float(string='Total without discount')
    total = fields.Float(string='Total')
    doctors_discounts = fields.Float('Discount(%)')
    after_discount = fields.Float('Discount Amount')
    other_discount = fields.Float('Other Discount')
    grand_total = fields.Float('Grand Total')
    advance = fields.Float('Advance')
    paid = fields.Float('Paid')
    due = fields.Float('Due')
    type = fields.Selection([('cash', 'Cash'), ('bank', 'Bank')], 'Payment Type')
    card_no = fields.Char('Card No.')
    bank_name = fields.Char('Bank Name')
    date = fields.Datetime('Date', readonly=True, default=None)
    user_id = fields.Many2one('res.users', string='Assigned to', select=True, track_visibility='onchange')
    state = fields.Selection([('pending', 'Pending'), ('activated', 'Admitted'), ('released', 'Released'), ('cancelled', 'Cancelled')], 'Status', default='pending', readonly=True)
    emergency_covert_time = fields.Datetime('Admission Convert time')
    old_journal = fields.Boolean('Old Journal')
    payment_type = fields.Many2one('payment.type', string='Payment Type')
    service_charge = fields.Float('Service Charge')
    to_be_paid = fields.Float('To be Paid')
    account_number = fields.Char('Account Number')
    father_name = fields.Char("Father's Name")
    mother_name = fields.Char("Mother's Name")
    religion = fields.Selection([('islam', 'Islam'), ('hindu', 'Hinduism'), ('buddhism', 'Buddhism'), ('christianity', 'Christianity')], 'Religion')
    blood_group = fields.Char('Blood Group')
    reffered_to_hospital = fields.Many2one('brokers.info', string='Referred to this hospital by')
    occupation = fields.Char('Occupation')
    business_address = fields.Char('Business Address')
    admitting_doctor = fields.Many2one('doctors.profile', string='Admitting Doctor')
    bed = fields.Char('Bed')
    received_by = fields.Char('Received/Registered By')
    clinic_diagnosis = fields.Char('Clinical Diagnosis')
    discount_remarks = fields.Char('Discount Remarks')
