from odoo import models, fields

class OpticsSale(models.Model):
    _name = 'optics.sale'
    _description = 'OpticsSale'

    name = fields.Char('Name')
    mobile = fields.Char(string='Mobile', readonly=True, store=False)
    patient_id = fields.Char(related='patient_name.patient_id', string='Patient Id', readonly=True)
    patient_name = fields.Many2one('patient.info', string='Patient Name', required=True, placeholder='Full Name')
    address = fields.Char('Address', store=False, placeholder='Address')
    age = fields.Char('Age', store=False)
    sex = fields.Char('Sex', store=False)
    right_eye_sph = fields.Char('Right Eye SPH')
    right_eye_cyl = fields.Char('Right Eye CYL')
    right_eye_axis = fields.Char('Right Eye AXIS')
    right_eye_sph_n = fields.Char('Right Eye SPH -N')
    right_eye_cyl_n = fields.Char('Right Eye CYL -N')
    right_eye_axis_n = fields.Char('Right Eye AXIS -N')
    left_eye_sph = fields.Char('Left Eye SPH')
    left_eye_cyl = fields.Char('Left Eye CYL')
    left_eye_axis = fields.Char('Left Eye AXIS')
    left_eye_sph_n = fields.Char('Left Eye SPH -N')
    left_eye_cyl_n = fields.Char('Left Eye CYL -N')
    left_eye_axis_n = fields.Char('Left Eye AXIS -N')
    delivery_date = fields.Date(string='Delivery Date')
    hard_cover = fields.Boolean('Cover', default=True)
    cell_pad = fields.Boolean('Cell Pad', default=True)
    frame_id = fields.Many2one('product.product', string='Frame')
    quantity = fields.Integer('Quantity')
    qty_available = fields.Integer('Stock Quantity', readonly=True)
    delivery_id = fields.Many2one('stock.picking', string='Delivery Challan')
    price = fields.Float('Price')
    optics_lens_sale_line_id = fields.One2many('optics.lens.sale.line', 'optics_sale_id')
    optics_sale_payment_line_id = fields.One2many('optics.sale.payment.line', 'optics_sale_payment_line_id')
    total = fields.Float(string='Total')
    doctors_discounts = fields.Float('Discount(%)')
    after_discount = fields.Float('Discount Amount')
    other_discount = fields.Float('Other Discount')
    grand_total = fields.Float('Grand Total')
    paid = fields.Float(string='Paid', required=True)
    card_no = fields.Char('Card No.')
    bank_name = fields.Char('Bank Name')
    due = fields.Float('Due')
    date = fields.Datetime('Date', readonly=True, default=None)
    state = fields.Selection([('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], 'Status', default='pending', readonly=True)
    payment_type = fields.Many2one('payment.type', string='Payment Type')
    payment_is_cash = fields.Boolean(related='payment_type.is_cash', string='Cash Payment')
    service_charge = fields.Float('Service Charge')
    to_be_paid = fields.Float('To be Paid')
    account_number = fields.Char('Account Number')
