#!/usr/bin/env python3
"""Reconcile the legacy export against the generated catalogue.

Answers the only question that matters after a re-organisation this large:
did any item the hospital was actually billing quietly disappear?

Every legacy name is either matched to a new item or listed under a MERGED /
DROPPED heading with the reason. Run with the legacy CSV path as argv[1].
"""

import csv
import difflib
import importlib
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from build_catalogue import SECTIONS  # noqa: E402

# Legacy name -> new xmlid, for the cases a name comparison cannot bridge.
# Anything listed here was a duplicate, a misspelling or a misfiled item.
MERGED = {
    'HBS': ('hbsag_screening', 'duplicate of the HBsAg screening test'),
    'S.GOT': ('ast_sgot', 'duplicate of AST (SGOT)'),
    'S.FREEITIN LEVEL': ('serum_ferritin', 'misspelling, duplicate of Serum Ferritin'),
    'S. Feritin': ('serum_ferritin', 'misspelling, duplicate of Serum Ferritin'),
    'Ferritin': ('serum_ferritin', 'duplicate of Serum Ferritin'),
    'S.IRON': ('serum_iron', 'duplicate of Serum Iron'),
    'S.TIBC': ('tibc', 'duplicate of TIBC'),
    'TIBC': ('tibc', 'kept'),
    'S.Cholesterol': ('serum_cholesterol', 'renamed'),
    'S.Trygleceride': ('serum_triglyceride', 'misspelling, duplicate of Serum Triglyceride'),
    'Triglycerides': ('serum_triglyceride', 'duplicate of Serum Triglyceride'),
    'S. AMYLASE': ('serum_amylase', 'renamed'),
    'S.Electrolytes': ('serum_electrolytes', 'renamed'),
    'S.Iron Profile': ('serum_iron_profile', 'renamed'),
    'S. Calcium': ('serum_calcium', 'renamed'),
    'S. Urea': ('serum_urea', 'renamed'),
    'S. eGFR': ('serum_egfr', 'renamed'),
    'S. Phosphate': ('serum_inorganic_phosphate', 'duplicate of Inorganic Phosphate'),
    'Inorganic Phoshate': ('serum_inorganic_phosphate', 'misspelling'),
    'Potassium': ('serum_potassium', 'renamed'),
    'Magnesium': ('serum_magnesium', 'renamed'),
    'Lactate': ('serum_lactate', 'renamed'),
    'Folic Acid': ('serum_folic_acid', 'renamed'),
    'Lipase': ('serum_lipase', 'renamed'),
    'BUN': ('blood_urea_nitrogen_bun', 'renamed'),
    'Uric Acid': ('serum_uric_acid', 'renamed'),
    'ALP Phosphatase': ('alkaline_phosphatase_alp', 'renamed'),
    'Gamma GT': ('gamma_gt_ggt', 'renamed'),
    'Protein-Electrophoresis': ('protein_electrophoresis', 'renamed'),
    'Protein electrophoresis': ('protein_electrophoresis', 'duplicate'),
    'TOTAL PROTEIN': ('total_protein', 'renamed'),
    'SERUM GLOBULIN': ('serum_globulin', 'renamed'),
    'SERUM A/G RATIO': ('serum_a_g_ratio', 'renamed'),
    'Serum: Albumin': ('serum_albumin', 'renamed'),
    'Urine: Albumin': ('urine_albumin', 'renamed'),
    'Urine: Micro-Albumin': ('urine_micro_albumin', 'renamed'),
    'BILIRUBIN (TOTAL)': ('serum_bilirubin_total', 'renamed'),
    'BILIRUBIN DIRECT/INDIRECT': ('serum_bilirubin_direct_indirect', 'renamed'),
    'Serum Bilirubin(total-direct-indirect)': ('serum_bilirubin_total_direct_indirect', 'renamed'),
    'Deprecated by IT (Electrolyte).': (None, 'explicitly deprecated in the legacy data'),
    'HBA1C': ('hba1c', 'renamed'),
    'OGTT': ('ogtt_full_fasting_1_hour_2_hours', 'renamed'),
    'OGTT (Fasting)': ('ogtt_fasting', 'kept'),
    'OGTT 2Hrs': ('ogtt_2_hours', 'renamed'),
    'FBS (Fasting Blood Sugar)': ('fasting_blood_sugar_fbs', 'renamed'),
    'RBS (Random Blood Sugar)': ('random_blood_sugar_rbs', 'renamed'),
    'RBS (Strip)': ('rbs_glucometer_strip', 'renamed'),
    'FBS(Strip)': ('fbs_glucometer_strip', 'renamed'),
    '2Hrs ABF(Strip)': ('2_hours_abf_glucometer_strip', 'renamed'),
    'Blood Sugar 2hrs ABF': ('blood_sugar_2_hours_abf', 'renamed'),
    '2 Hours ABF': ('blood_sugar_2_hours_abf', 'duplicate'),
    'Blood Sugar Fasting & 2hrs ABF': ('blood_sugar_fasting_2_hours_abf', 'renamed'),
    'Blood Sugar 2hrs ABF & 2hrs AL (After Lunch)': ('blood_sugar_2_hours_abf_2_hours_after_lunch', 'renamed'),
    'Blood Sugar 2hrs After Lunch': ('blood_sugar_2_hours_after_lunch', 'renamed'),
    'Fasting Blood Sugar and 2 Hours After 75gm Glucose (FBS-2h 75g)': ('fasting_blood_sugar_2_hours_after_75g_glucose', 'renamed'),
    'RBS With Corosponding Urine': ('rbs_with_corresponding_urine', 'misspelling'),
    '75 gm Glucose': ('cons_glucose_75g', 'moved to Consumables'),
    'CCR': ('creatinine_clearance_ccr', 'renamed'),
    'Renal Function Test (RFT)': ('renal_function_test_rft', 'kept'),
    'LFT': ('liver_function_test_lft', 'renamed'),
    'ALT (SGPT)': ('alt_sgpt', 'kept'),
    'AST (SGOT)': ('ast_sgot', 'kept'),
    'Urine ACR': ('urine_acr_albumin_creatinine_ratio', 'renamed'),
    'Urine PCR': ('urine_pcr_protein_creatinine_ratio', 'renamed'),
    '24 hrs urinary total protein': ('24_hours_urinary_total_protein', 'renamed'),
    'Urinary electrolytes': ('urinary_electrolytes', 'renamed'),
    'Ascitic/CSF/Pleural Fluid for Biochemistry': ('ascitic_csf_pleural_fluid_for_biochemistry', 'kept'),
    'CSF for protein, Glucose, TC, DC, ADA': ('csf_for_protein_glucose_tc_dc_ada', 'kept'),
    'Serum ACE (Angiotensin Converting Enzime)': ('serum_ace_angiotensin_converting_enzyme', 'misspelling'),
    'S. ACE LEVEL': ('serum_ace_angiotensin_converting_enzyme', 'duplicate'),
    'Ammonia': ('serum_ammonia', 'renamed'),
    'Homa IR': ('homa_ir_insulin_resistance_index', 'renamed'),
    'Anti-Cardiolipin AB': ('anti_cardiolipin', 'moved to Immunology'),
    'Anti SS-A Antibody': ('anti_ss_a', 'moved to Immunology'),
    'Anti SS-B Antibody': ('anti_ss_b', 'moved to Immunology'),
    'Serum C3': ('serum_c3', 'moved to Immunology'),
    'Serum C4': ('serum_c4', 'moved to Immunology'),
    'IGM for Herpes Simplex': ('herpes_simplex_igm', 'moved to Immunology'),
    'IGG for Herpes Simplex': ('herpes_simplex_igg', 'moved to Immunology'),
    'DHT': ('dht', 'moved to Hormone'),
    'ACTH': ('acth', 'moved to Hormone'),
    'Growth Hormone': ('growth_hormone', 'moved to Hormone'),
    'S. GH': ('growth_hormone', 'duplicate, moved to Hormone'),
    'CPK': ('cpk_creatine_phosphokinase', 'moved to Biochemistry'),
    'LDH': ('ldh_lactate_dehydrogenase', 'moved to Biochemistry'),
    'CORTISOL (BASAL-9:00 AM)': ('cortisol_am', 'moved to Hormone'),
    'CORTISOL (Evening-5:00 PM)': ('cortisol_pm', 'moved to Hormone'),
    'Transferrin saturation (TSAT)': ('transferrin_saturation_tsat', 'kept'),
    'Free Testosteron': ('free_testosterone', 'misspelling, moved to Hormone'),
    'Testosterone': ('testosterone_total', 'renamed'),
    'PSA': ('psa_total', 'renamed'),
    'tPSA': ('tpsa_fpsa', 'renamed'),
    'ESTEOGEN': ('oestrogen_estradiol', 'misspelling'),
    'OESTROGEN': ('oestrogen_estradiol', 'renamed'),
    'PROGESTERONE': ('progesterone', 'renamed'),
    'PTH( Parathyroid)': ('pth', 'renamed'),
    'Prolactin': ('prolactin', 'kept'),
    'LH': ('lh', 'kept'),
    'FSH': ('fsh', 'kept'),
    'AMH': ('amh', 'renamed'),
    'TSH': ('tsh', 'kept'),
    'T3': ('t3', 'renamed'),
    'T4': ('t4', 'renamed'),
    'FT3': ('ft3', 'renamed'),
    'FT4': ('ft4', 'renamed'),
    # --- haematology
    'Hb%': ('haemoglobin', 'renamed'),
    'Haemoglobin': ('haemoglobin', 'duplicate'),
    'Hemoglobin': ('haemoglobin', 'misspelling, duplicate'),
    'HCT': ('haematocrit', 'renamed'),
    'PCT': ('plateletcrit', 'renamed'),
    'Platelet  Count': ('platelet_count', 'renamed'),
    'TC,DC': ('tc_dc', 'renamed'),
    'CBC': ('cbc', 'renamed'),
    'PBF': ('blood_film_pbf', 'duplicate of Blood Film (PBF)'),
    'Blood Film (PBF)': ('blood_film_pbf', 'kept'),
    'Circulating Eosinophils (T C E)': ('circulating_eosinophil_count', 'renamed'),
    'Raticulocyte Count': ('reticulocyte_count', 'misspelling, duplicate'),
    'Reticulocyte Count': ('reticulocyte_count', 'kept'),
    'HB% Electro Phoresis': ('haemoglobin_electrophoresis', 'renamed'),
    'HB-ELECTROPHORESIS': ('haemoglobin_electrophoresis', 'duplicate'),
    'Prothombintime': ('prothrombin_time', 'misspelling'),
    'APTT': ('aptt', 'renamed'),
    'BT, CT': ('bt_ct', 'renamed'),
    'Fibrionogen Level': ('fibrinogen_level', 'misspelling, moved to Haematology'),
    'D-Dimer': ('d_dimer', 'moved to Haematology'),
    'Fibrin Degradation Products (FDP)': ('fdp', 'renamed'),
    # --- clinical pathology
    'Urine R/M/E': ('urine_rme', 'renamed'),
    'Stool  R/M/E': ('stool_rme', 'renamed'),
    'Stool R/s': ('stool_reducing_substance', 'reinterpreted - the legacy record held an antibiotic list, not a routine'),
    'Stool OBT': ('stool_obt', 'renamed'),
    'Semen Analysis': ('semen_analysis', 'kept'),
    'Mantoux Test (MT)': ('leih19.examination_entry_mantoux', 'adopted leih19 build'),
    'Urine For Ketone Bodies': ('urine_for_ketone_bodies', 'renamed'),
    'HsCRP': ('hscrp', 'renamed'),
    'C-Peptide': ('c_peptide', 'moved to Biochemistry'),
    'Urinary Osmolality': ('urinary_osmolality', 'moved to Biochemistry'),
    'Serum Osmolality': ('serum_osmolality', 'moved to Biochemistry'),
    'Random Insulin': ('random_insulin', 'moved to Biochemistry'),
    'IOP': ('intraocular_pressure', 'renamed'),
    'BP': ('blood_pressure', 'renamed'),
    'Homocysteine': ('homocysteine', 'moved to Biochemistry'),
    # --- serology / immunology
    'Widal Test': ('widal_test', 'kept'),
    'HBsAg (Screening Test)': ('hbsag_screening', 'renamed'),
    'HBs Ag': ('hbsag_elisa', 'renamed'),
    'HBsAg (Quantitative)': ('hbsag_quantitative', 'kept'),
    'Blood Group': ('blood_group', 'renamed'),
    'RA': ('ra_test_qualitative', 'duplicate'),
    'RA Test': ('ra_test_qualitative', 'renamed'),
    'RA Factor': ('ra_test_qualitative', 'duplicate'),
    'R A Test( Rheumatoid Arthritis)': ('ra_test_qualitative', 'duplicate'),
    'RA Test (quantitative)': ('ra_test_quantitative', 'renamed'),
    'Dengue IgG/IgM': ('dengue_igg_igm', 'renamed'),
    'Dengue lgM': ('dengue_igm', 'misspelling'),
    'Dengue NS1 Ag (ICT)': ('dengue_ns1', 'renamed'),
    'Pregnancy Test': ('pregnancy_test', 'renamed'),
    'Rubella IgG': ('rubella_igg', 'kept'),
    'Rubella IgM': ('rubella_igm', 'kept'),
    'HCV(Screening Test)': ('anti_hcv_screening', 'renamed'),
    'Anti HCV': ('anti_hcv', 'renamed'),
    'Malaria Parasite(MP)': ('malaria_parasite', 'renamed'),
    'ICT for Malarial': ('ict_malaria', 'misspelling'),
    'Triple  Antigen': ('triple_antigen', 'renamed'),
    'Febrile Antigen': ('febrile_antigen', 'renamed'),
    'ANTI-HPYLORI IGG': ('anti_h_pylori_igg', 'renamed'),
    'H.pylori Test': ('h_pylori_stool_antigen', 'renamed'),
    'RH-antibody Titre': ('rh_antibody_titre', 'renamed'),
    "Commb's": ('coombs_test', 'misspelling'),
    'CRP': ('crp', 'kept'),
    'VDRL': ('vdrl', 'kept'),
    'TPHA (Screening Test)': ('tpha', 'renamed'),
    'HIV 1,2 ( Screening Test )': ('hiv_screening', 'renamed'),
    'Anti HIV': ('anti_hiv_elisa', 'renamed'),
    'ASO Titre': ('aso_titre', 'kept'),
    'Chickungunya igG, igM': ('chikungunya_igg_igm', 'misspelling'),
    'Interleukin-6 ( IL-6)': ('interleukin_6', 'renamed'),
    'ATP-ALPHA-FETO-PROTEIN': ('afp', 'duplicate of AFP'),
    'AFP': ('afp', 'kept'),
    'B-HCG': ('beta_hcg', 'renamed'),
    'CA-125': ('ca_125', 'kept'),
    'CA-19.9': ('ca_19_9', 'kept'),
    'CA-15.3': ('ca_15_3', 'kept'),
    'CEA': ('cea', 'kept'),
    'HLA-B27': ('hla_b27', 'kept'),
    'ADA': ('ada', 'kept'),
    'ANTI-DS DNA': ('anti_ds_dna', 'renamed'),
    'ANTI-CCP': ('anti_ccp', 'renamed'),
    'ANA': ('ana', 'kept'),
    'VIT B-12': ('vitamin_b12', 'duplicate'),
    'Vitamin B12': ('vitamin_b12', 'kept'),
    'ANTI-HEV IGM': ('anti_hev_igm', 'renamed'),
    'Anti HEV': ('anti_hev', 'renamed'),
    'Anti Hbs': ('anti_hbs', 'renamed'),
    'Anti- HBV': ('anti_hbs', 'duplicate of Anti-HBs'),
    'ANTI-HBC TOTAL': ('anti_hbc_total', 'renamed'),
    'ANTI-HBE TOTAL': ('anti_hbe_total', 'renamed'),
    'HBeAg': ('hbeag', 'kept'),
    'Anti HAV': ('anti_hav', 'renamed'),
    'ANTI-HAV IGM': ('anti_hav_igm', 'renamed'),
    'SBNP': ('nt_pro_bnp', 'duplicate of NT-proBNP'),
    'NT-Pro BNP': ('nt_pro_bnp', 'renamed'),
    'Total IgE': ('total_ige', 'kept'),
    'Procalcitonin': ('procalcitonin', 'kept'),
    'Vitamin D': ('vitamin_d', 'renamed'),
    'CANCA': ('canca', 'renamed'),
    'PANCA': ('panca', 'renamed'),
    'IgG ,IgM for Toxo': ('toxoplasma_igg_igm', 'renamed'),
    'Torch Anti-Body': ('torch_panel', 'renamed'),
    'QuantiFERON-TB Gold': ('quantiferon_tb_gold', 'renamed'),
    'IGRA (Quantiferon TB Gold Test)': ('quantiferon_tb_gold', 'duplicate'),
    'Anti HSV-1 IgG & IgM': ('anti_hsv1_igg_igm', 'kept'),
    'Anti-Thyroid Antibodies (TPO)': ('anti_tpo', 'renamed'),
    'Anti - Thyroid Ab Test': ('anti_thyroid_ab_panel', 'renamed'),
    'ACH Receptor Antibody': ('ach_receptor_antibody', 'renamed'),
    'TRAB': ('trab', 'kept'),
    'Gene-X-Pert': ('genexpert_mtb_rif', 'renamed, moved to Microbiology'),
    'LPH': (None, 'unidentifiable legacy code - no test could be established from the name'),
    # --- microbiology
    'Urine For C/S': ('urine_cs', 'renamed'),
    'Blood For C/S': ('blood_cs', 'renamed'),
    'Stool For C/S': ('stool_cs', 'renamed'),
    'Sputum For C/S': ('sputum_cs', 'renamed'),
    'Wound Swab C/s': ('wound_swab_cs', 'renamed'),
    'Pus for C/S': ('pus_cs', 'renamed'),
    'Tracheal aspirate for c/s': ('tracheal_aspirate_cs', 'duplicate'),
    'Tracheal Aspirate / Swab for C/S': ('tracheal_aspirate_cs', 'kept'),
    'Catheter Tip CS': ('catheter_tip_cs', 'renamed'),
    'Conjunctival Swab For C/S (Right Eye)': ('conjunctival_swab_cs_right', 'renamed'),
    'Conjunctival Swab For C/S(Left Eye)': ('conjunctival_swab_cs_left', 'renamed'),
    'Corneal Scrapping for C/S': ('corneal_scraping_cs', 'misspelling'),
    'Corneal Scrapping for KOH (Right Eye)': ('corneal_scraping_koh_right', 'misspelling'),
    'Corneal Scrapping for KOH-Left Eye': ('corneal_scraping_koh_left', 'misspelling'),
    'Gram Staining': ('gram_staining', 'kept'),
    'Sputum For Gram Staining': ('sputum_gram_staining', 'renamed'),
    'AFB': ('afb_staining', 'renamed'),
    'RTR PCR (Covid-19)': ('rt_pcr_covid19', 'renamed'),
    'PCR For zika, dengue & Chikungunya Virus': ('pcr_zika_dengue_chikungunya', 'renamed'),
    'Urine for Toxicology': ('urine_toxicology_screen', 'renamed'),
    'Amphetamine': ('amphetamine_urine', 'renamed'),
    'Benzodiazepines': ('benzodiazepines_urine', 'renamed'),
    'Cannabinoids': ('cannabinoids_urine', 'renamed'),
    'Opiates': ('opiates_urine', 'renamed'),
    # --- cytology / transfusion
    "Pap's Smear for Cytology": ('paps_smear_cytology', 'kept'),
    'Cross Matching + Screening + Drawing': ('cross_matching_screening_drawing', 'kept'),
    'Blood Bag Set': ('cons_blood_bag_set', 'moved to Consumables'),
    # --- imaging
    'ECG': ('ecg', 'renamed'),
    'Echo-2D': ('echo_2d', 'renamed'),
    'Echo Color Doppler': ('echo_colour_doppler', 'renamed'),
    'Portable Echocardiography': ('echo_portable', 'renamed, moved to Echocardiography'),
    'BMD': ('bmd', 'renamed, moved to X-Ray'),
    'MRA of Neck Vessel': ('mra_neck_vessels', 'renamed, moved to MRI'),
    'USG W/A 2D': ('usg_whole_abdomen', 'renamed'),
    'USG OF W/A, WITH MCC + PVR': ('usg_whole_abdomen_mcc_pvr', 'renamed'),
    'USG Of Upper Abdomen /HBS': ('usg_upper_abdomen', 'renamed'),
    'USG of Upper Abdomen /HBS': ('usg_upper_abdomen', 'renamed'),
    'Usg Of HBS Panonex': ('usg_hbs', 'renamed'),
    'USG of Lower Abdomenm': ('usg_lower_abdomen', 'misspelling'),
    'USG of Pelvis': ('usg_pelvis', 'kept'),
    'Usg Of TVS': ('usg_tvs', 'renamed'),
    'USG of KUB region': ('usg_kub_region', 'renamed'),
    'USG of KUB, Prostate and PVR': ('usg_kub_prostate_pvr', 'renamed'),
    'USG of KUB, Prostate PVR, MCC': ('usg_kub_prostate_pvr_mcc', 'renamed'),
    'USG of Pregnancy Profile': ('usg_pregnancy_profile', 'kept'),
    'USG OF ANOMALY SCAN': ('usg_anomaly_scan', 'renamed'),
    'Bio-physical Profile': ('usg_biophysical_profile', 'renamed'),
    'USG OF Pregnancy Biophysical Profile': ('usg_pregnancy_biophysical_profile', 'renamed'),
    'USG OF THYROID-2D': ('usg_thyroid', 'renamed'),
    'USG Of Neck': ('usg_neck', 'renamed'),
    'Usg Of Single Breast': ('usg_single_breast', 'renamed'),
    'Usg Of Both Breast': ('usg_both_breasts', 'renamed'),
    'USG OF BOTH AXILLARY REGION': ('usg_both_axillary_regions', 'renamed'),
    'Usg of brain': ('usg_brain', 'renamed'),
    'Ultrasonogram (4D USG)': ('usg_4d', 'renamed'),
    'Portable USG': ('usg_portable', 'renamed'),
    'Dental X-Ray': ('dental_xray', 'renamed'),
    'RVG Dental X-Ray': ('dental_rvg_xray', 'renamed'),
    # --- dental
    'Normal Scaling': ('dental_normal_scaling', 'kept'),
    'Scaling with Polishing (SP)': ('dental_scaling_polishing', 'renamed'),
    'Scaling & Polishing + currettage + Deep currettage': ('dental_scaling_curettage', 'misspelling'),
    'Treatment Filling (TF)': ('dental_treatment_filling', 'renamed'),
    'Light Cure Filling Type-1 (LCF)': ('dental_lcf_type1', 'renamed'),
    'Light Cure Filling Type -2(LCF)': ('dental_lcf_type2', 'renamed'),
    'Light Cure Filling Type-3(LCF)': ('dental_lcf_type3', 'renamed'),
    'Tooth Color(GI)': ('dental_tooth_colour_gi', 'renamed'),
    'Permanent Teeth ( Glass lonomer Filling )': ('dental_permanent_gi_filling', 'misspelling'),
    'Dental Dressing': ('dental_dressing', 'kept'),
    'RCT (Anterior)': ('dental_rct_anterior', 'kept'),
    'RCT (posterior)': ('dental_rct_posterior', 'renamed'),
    'Re-RCT': ('dental_re_rct', 'kept'),
    'Root Canal Treatment Ant. (Each Visit) (RCT)': ('dental_rct_ant_each_visit', 'renamed'),
    'Root Canal Treatment Ant. (2nd) (RCT)': ('dental_rct_ant_2nd_visit', 'renamed'),
    'Root Canal Treatment Ant. (4th) (RCT)': ('dental_rct_ant_4th_visit', 'renamed'),
    'Root Canel Treatment (Endo Motor) Each Visit (RCT)': ('dental_rct_endo_each_visit', 'misspelling'),
    'Root Canal Treatment (Endo Motor) Each Visit-1 (RCT)': ('dental_rct_endo_visit1', 'renamed'),
    'Root Canal Treatment (Endo Motor) Each Visit-2 (RCT)': ('dental_rct_endo_visit2', 'renamed'),
    'Root Canal Treatment (Endo Motor) Each Visit-4 (RCT)': ('dental_rct_endo_visit4', 'renamed'),
    'Root Canal Treatement Endo. (RCT)': ('dental_rct_endo_complete', 'misspelling'),
    'Root canel treatment (infection) (RCT)': ('dental_rct_infection', 'misspelling'),
    'Pulpectomy': ('dental_pulpectomy', 'kept'),
    'Pulpotomy': ('dental_pulpotomy', 'kept'),
    'Apisectomy 2 Teeth': ('dental_apicectomy_2', 'misspelling'),
    'Apisectomy 4 Teeth': ('dental_apicectomy_4', 'misspelling'),
    'Milk Teeth Extraction': ('dental_milk_teeth_extraction', 'kept'),
    'Permanent teeth extraction (ant.) Simple': ('dental_extraction_anterior_simple', 'renamed'),
    'Permanent teeth extraction (Post.) Simple': ('dental_extraction_posterior_simple', 'renamed'),
    'Surgical teeth ext upper': ('dental_surgical_extraction_upper', 'renamed'),
    'Surgical teeth ext lower': ('dental_surgical_extraction_lower', 'renamed'),
    'Surgical Ext lower/mesic angular': ('dental_surgical_extraction_mesioangular', 'misspelling'),
    'Surgical Extraction Horizontal/Angular/Vertical': ('dental_surgical_extraction_hav', 'renamed'),
    'Cap Visit': ('dental_cap_visit', 'kept'),
    'Cast Post (Each Unit) Crown': ('dental_cast_post_crown', 'renamed'),
    'Porcelain Cap (1 Unit) A': ('dental_porcelain_cap', 'renamed'),
    'Zirconia Crown': ('dental_zirconia_crown', 'kept'),
    'Partial Denture (Per Unit) (PD)': ('dental_partial_denture', 'renamed'),
    'complete denture ( Upper)': ('dental_complete_denture_upper', 'renamed'),
    'complete denture ( Lower)': ('dental_complete_denture_lower', 'renamed'),
    'Complete Denture': ('dental_complete_denture_both', 'renamed'),
    'Gingi Vectomy (per teeth)': ('dental_gingivectomy', 'misspelling'),
    # --- OT / indoor / services
    'OT Charge (First Hour)': ('ot_charge_first_hour', 'kept'),
    'OT Charge - Second Hour': ('ot_charge_second_hour', 'renamed'),
    'OT Charge with Sedation': ('ot_charge_with_sedation', 'kept'),
    'Outdoor Surgeon OT Charge (Package)': ('ot_outdoor_surgeon_package', 'renamed'),
    'Team Charge (OT)': ('ot_team_charge', 'renamed'),
    'OT Team Charge -2': ('ot_team_charge_2', 'renamed'),
    'Surgeon Team Charge': ('ot_surgeon_team_charge', 'kept'),
    'Surgeon team charge': ('ot_surgeon_team_charge', 'duplicate'),
    'Ot Assistant': ('ot_assistant_charge', 'renamed'),
    'Assistant Doctor Free': ('ot_assistant_doctor_fee', 'misspelling of Fee'),
    'Anesthesiologist Fee': ('ot_anaesthesiologist_fee', 'renamed'),
    'Anesthesia Doctor Free': ('ot_anaesthesia_doctor_fee', 'misspelling of Fee'),
    'Isoflurance Charge': ('ot_isoflurane_charge', 'misspelling'),
    'Labour Room Charge': ('ot_labour_room_charge', 'kept'),
    'Ligasure  machine charge': ('ot_ligasure_machine', 'renamed'),
    'Laparoscopy Machine Charge': ('ot_laparoscopy_machine', 'kept'),
    'Circular Stapler': ('ot_circular_stapler', 'kept'),
    'Cutting Stapler': ('ot_cutting_stapler', 'kept'),
    'Implant Charge': ('ot_implant_charge', 'kept'),
    'Post Operative Charge (First Four Hours)': ('ot_post_op_first_4h', 'renamed'),
    'Post Operative Charge (More Than Four Hours)': ('ot_post_op_over_4h', 'renamed'),
    'Monitor Charge for Post Operative (1 Day)': ('ot_post_op_monitor', 'renamed'),
    'Oxygen Charge for Post Operative': ('ot_post_op_oxygen', 'kept'),
    'Socket Reconstructions A': ('ot_socket_reconstruction_a', 'renamed'),
    'Socket Reconstructions B': ('ot_socket_reconstruction_b', 'renamed'),
    'Socket Reconstructions C': ('ot_socket_reconstruction_c', 'renamed'),
    'Canalicular Reconstructions A': ('ot_canalicular_reconstruction_a', 'renamed'),
    'Canalicular Reconstructions B': ('ot_canalicular_reconstruction_b', 'renamed'),
    'Punctoplasty A': ('ot_punctoplasty_a', 'renamed'),
    'Punctoplasty B': ('ot_punctoplasty_b', 'renamed'),
    'BCL': ('ot_bandage_contact_lens', 'renamed'),
    'Reposition of IOL for OPD Patients': ('ot_reposition_iol', 'renamed'),
    'Reposition of IOL for OPD Patients(Lions Case)': ('ot_reposition_iol_lions', 'renamed'),
    'Procedure Charge - Local Anesthesia Only': ('ot_procedure_local_anaesthesia', 'renamed'),
    'Procedure Charge - Local Anaesthesia Only': ('ot_procedure_local_anaesthesia', 'duplicate'),
    'Lumbar Puncher': ('ot_lumbar_puncture', 'misspelling'),
    'Copper-T Charge': ('ot_copper_t', 'renamed'),
    'Admission Charge': ('indoor_admission_charge', 'kept'),
    'Admission Fee (Outside)': ('indoor_admission_fee_outside', 'renamed'),
    'Ward Bed Charge': ('indoor_ward_bed_charge', 'kept'),
    'Cabin Charge': ('indoor_cabin_charge', 'kept'),
    'Share Cabin Charge': ('indoor_share_cabin_charge', 'kept'),
    'HDU (Bed Charge)': ('indoor_hdu_bed_charge', 'renamed'),
    'Baby Cot Bed': ('indoor_baby_cot_bed', 'kept'),
    'Food Cost': ('indoor_food_cost', 'kept'),
    "Consultant's Fee": ('indoor_consultant_fee', 'renamed'),
    'Service Charge': ('indoor_service_charge', 'kept'),
    'Medicine Charge': ('indoor_medicine_charge', 'kept'),
    'Medicine total': ('indoor_medicine_total', 'renamed'),
    'Out Medicine Fee': ('indoor_out_medicine_fee', 'kept'),
    'Ambulance Service Fee': ('indoor_ambulance_service_fee', 'kept'),
    'Infusion Pump Charge (Per Day)': ('indoor_infusion_pump_charge', 'kept'),
    'Other Charges': ('indoor_other_charges', 'kept'),
    'Injection Pushing': ('svc_injection_pushing', 'kept'),
    'Dressing (Minor)': ('svc_dressing_minor', 'kept'),
    'Dressing (Intermediate)': ('svc_dressing_intermediate', 'kept'),
    'Dressing (Major)': ('svc_dressing_major', 'kept'),
    'iv canula': ('svc_iv_cannula', 'renamed'),
    'Photo Therapy(/hour)': ('svc_photo_therapy', 'renamed'),
    'Oxygen Above 5 Litre': ('svc_oxygen_above_5l', 'renamed'),
    'EMO Charge': ('svc_emo_charge', 'renamed'),
    'Emergency Observation': ('svc_emergency_observation', 'kept'),
    'Hemo Dialysis Charge': ('svc_haemodialysis', 'renamed'),
    'Hemo Dialysis Charge (Reuse)': ('svc_haemodialysis_reuse', 'renamed'),
    'Birth Certificate Fee': ('svc_birth_certificate_fee', 'kept'),
    'Investigation Charge': ('svc_investigation_charge', 'renamed'),
    'Needle for Vacuette- 01 Unit': ('cons_needle_vacuette', 'renamed'),
    'Disposable for Vacuette': ('cons_disposable_vacuette', 'kept'),
    'Disposable for Vacuette-01 Unit': ('cons_disposable_vacuette_1', 'renamed'),
    'Disposable for Vacuette-02 Unit': ('cons_disposable_vacuette_2', 'renamed'),
    'Disposable for Vacuette-03 Unit': ('cons_disposable_vacuette_3', 'renamed'),
    'Basic Health Checkup Package (RBS, Creatinine, Lipid Profile, SGPT, CBC, '
    'ECG, USG W/A, One Consultation Of Medicine Consultant)':
        ('pkg_basic_health_checkup', 'renamed - contents moved out of the name'),
    'Executive Health Checkup Package (RBS, HbA1c, S. Creatinine, Uric Acid, '
    'TSH, Lipid Profile, SGPT, SGOT, CBC, ECG, USG of W/A, One Consultation Of '
    'Medicine Consultant)':
        ('pkg_executive_health_checkup', 'renamed - contents moved out of the name'),
}


def main(csv_path):
    catalogue = {}
    for spec, _f, _t in SECTIONS:
        for item in importlib.import_module('items.%s' % spec).ITEMS:
            catalogue[item['xmlid']] = item['name']

    legacy = []
    seen = set()
    with open(csv_path) as handle:
        for row in csv.DictReader(handle):
            if row['id'] and row['name'].strip() not in seen:
                seen.add(row['name'].strip())
                legacy.append((row['name'].strip(), row['rate']))

    matched, merged, dropped, unresolved = [], [], [], []
    for name, rate in legacy:
        if name in MERGED:
            target, reason = MERGED[name]
            if target is None:
                dropped.append((name, rate, reason))
            elif target in catalogue or target.startswith('leih19.'):
                merged.append((name, target, reason))
            else:
                unresolved.append((name, 'maps to unknown xmlid %r' % target))
            continue
        key = re.sub(r'[^a-z0-9]+', '_', name.lower()).strip('_')[:60].rstrip('_')
        if key in catalogue:
            matched.append((name, key))
        else:
            close = difflib.get_close_matches(key, catalogue, n=1, cutoff=0.75)
            unresolved.append((name, 'nearest: %s' % (close[0] if close else 'none')))

    print('legacy unique items : %d' % len(legacy))
    print('new catalogue items : %d' % len(catalogue))
    print('  matched by name   : %d' % len(matched))
    print('  merged / renamed  : %d' % len(merged))
    print('  intentionally dropped: %d' % len(dropped))
    print('  UNRESOLVED        : %d' % len(unresolved))
    for name, _rate, reason in dropped:
        print('  DROPPED  %-55s %s' % (name[:55], reason))
    for name, reason in unresolved:
        print('  UNRESOLVED  %-50s %s' % (name[:50], reason))
    return 1 if unresolved else 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1]))
