"""Short names for the xmlids the item specs reference.

Keeps the spec files readable: ``dept=BIOCHEM`` rather than a bare string that
a typo would turn into a silent load failure at install time.
"""

# --- departments -----------------------------------------------------------
BIOCHEM      = 'dept_biochemistry'
HAEM         = 'dept_haematology'
CLINPATH     = 'dept_clinical_pathology'
SEROLOGY     = 'dept_serology'
IMMUNO       = 'dept_immunology'
HORMONE      = 'dept_hormone'
MICRO        = 'dept_microbiology'
HISTOCYTO    = 'dept_histocytopathology'
TRANSFUSION  = 'dept_transfusion'
XRAY         = 'dept_xray'
USG          = 'dept_usg'
CT           = 'dept_ct'
MRI          = 'dept_mri'
ECG          = 'dept_ecg'
ECHO         = 'dept_echo'
DENTAL       = 'dept_dental'
OT           = 'dept_ot'
INDOOR       = 'dept_indoor'
EMERGENCY    = 'dept_emergency'
DIALYSIS     = 'dept_dialysis'
NURSING      = 'dept_nursing'
PACKAGE      = 'dept_package'
CONSUMABLE   = 'dept_consumable'

# --- revenue accounts ------------------------------------------------------
AC_BIOCHEM      = 'account_income_biochemistry'
AC_HAEM         = 'account_income_haematology'
AC_CLINPATH     = 'account_income_clinical_pathology'
AC_SEROLOGY     = 'account_income_serology'
AC_IMMUNO       = 'account_income_immunology'
AC_HORMONE      = 'account_income_hormone'
AC_MICRO        = 'account_income_microbiology'
AC_HISTOCYTO    = 'account_income_histocytopathology'
AC_TRANSFUSION  = 'account_income_transfusion'
AC_XRAY         = 'account_income_xray'
AC_USG          = 'account_income_usg'
AC_CT           = 'account_income_ct'
AC_MRI          = 'account_income_mri'
AC_ECG          = 'account_income_ecg'
AC_ECHO         = 'account_income_echo'
AC_DENTAL       = 'account_income_dental'
AC_OT           = 'account_income_ot'
AC_INDOOR       = 'account_income_indoor'
AC_EMERGENCY    = 'account_income_emergency'
AC_DIALYSIS     = 'account_income_dialysis'
AC_NURSING      = 'account_income_nursing'
AC_PACKAGE      = 'account_income_package'
AC_CONSUMABLE   = 'account_income_consumable'
AC_OTHER        = 'account_income_other'

# --- tubes / containers ----------------------------------------------------
T_CULTURE  = 'tube_blood_culture'
T_BLUE     = 'tube_light_blue'
T_RED      = 'tube_red'
T_GOLD     = 'tube_gold_sst'
T_GREEN    = 'tube_green'
T_EDTA     = 'tube_lavender'
T_GREY     = 'tube_grey'
T_URINE    = 'tube_urine_container'
T_STOOL    = 'tube_stool_container'
T_SWAB     = 'tube_swab'
T_POT      = 'tube_sterile_pot'
T_FORMALIN = 'tube_histo_formalin'

# --- specimen material -----------------------------------------------------
SP_BLOOD    = 'sample_whole_blood'
SP_SERUM    = 'sample_serum'
SP_PLASMA   = 'sample_plasma'
SP_URINE    = 'sample_urine'
SP_URINE24  = 'sample_urine_24h'
SP_STOOL    = 'sample_stool'
SP_SPUTUM   = 'sample_sputum'
SP_SEMEN    = 'sample_semen'
SP_CSF      = 'sample_csf'
SP_FLUID    = 'sample_body_fluid'
SP_SWAB     = 'sample_swab'
SP_TISSUE   = 'sample_tissue'
SP_SMEAR    = 'sample_smear'
SP_CORNEA   = 'sample_corneal_scraping'
SP_CATHETER = 'sample_catheter_tip'

# --- methods ---------------------------------------------------------------
M_PHOTO    = 'method_photometry'
M_ISE      = 'method_ise'
M_CLIA     = 'method_clia'
M_ELISA    = 'method_elisa'
M_ICT      = 'method_ict'
M_AGGL     = 'method_agglutination'
M_IMPED    = 'method_impedance'
M_MICRO    = 'method_microscopy'
M_CULTURE  = 'method_culture'
M_GRAM     = 'method_gram_stain'
M_ZN       = 'method_zn_stain'
M_KOH      = 'method_koh'
M_PCR      = 'method_pcr'
M_HPLC     = 'method_hplc'
M_CE       = 'method_electrophoresis'
M_COAG     = 'method_coagulometry'
M_PAP      = 'method_papanicolaou'
M_MANUAL   = 'method_manual'

# --- instruments -----------------------------------------------------------
I_CHEM   = 'instrument_chem_analyzer'
I_ISE    = 'instrument_electrolyte'
I_IMM    = 'instrument_immunoassay'
I_HAEM   = 'instrument_haematology'
I_COAG   = 'instrument_coagulometer'
I_URINE  = 'instrument_urine_analyzer'
I_MICRO  = 'instrument_microscope'
I_INCUB  = 'instrument_incubator'
I_HPLC   = 'instrument_hba1c'
I_PCR    = 'instrument_pcr'
I_GLUCO  = 'instrument_glucometer'
