{
    'name': 'LEIS OPD Flow',
    'summary': 'Doctor sessions, serial appointments, arrival -> patient -> OPD '
               'billing, prescription templates and pharmacy/lab fulfilment',
    'version': '19.0.1.0',
    'author': 'Mufti Muntasir Ahmed',
    'depends': ['leih19', 'leih_patient', 'point_of_sale'],
    'data': [
        'security/ir.model.access.csv',
        'data/appointment_sequence.xml',
        'data/appointment_cn_sequence.xml',
        'data/doctor_prescription_sequence.xml',
        'data/medicine_data.xml',
        'views/doctor_schedule_views.xml',
        'views/res_company_views.xml',
        'wizard/appointment_arrival_wizard_views.xml',
        'reports/doctor_collection_report.xml',
        'wizard/doctor_collection_report_wizard_views.xml',
        'views/appointment_booking_views.xml',
        'views/appointment_queue_views.xml',
        'views/prescription_template_views.xml',
        'views/doctor_prescription_views.xml',
        'views/bill_register_views.xml',
        'reports/prescription_report.xml',
        'reports/appointment_token_report.xml',
        'views/menus.xml',
    ],
    'license': 'LGPL-3',
    'application': False,
}
